name: launchpad
recipe: wordpress
config:
  php: '8.0'
  via: nginx
  webroot: public
  database: mysql
  xdebug: false
#  config:
#      php: .vscode/php.ini
keys: false
#env_file:
#  - .env
services:
  node:
    type: node:20
  appserver:
#    config:
#      php: config/php.ini # Use a custom php.ini file.
    overrides:
      environment:
        XDEBUG_MODE: 'debug,develop,profile'
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
#  phpmyadmin:
#    type: phpmyadmin
#    hosts:
#      - database
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  npm:
    service: node
  node:
    service: node
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo